/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ProdutoRouteImport } from './routes/produto'
import { Route as TrocasRouteImport } from './routes/trocas'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ToteSlugRouteImport } from './routes/tote.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoRoute = ProdutoRouteImport.update({
  id: '/produto',
  path: '/produto',
  getParentRoute: () => rootRouteImport,
} as any)
const TrocasRoute = TrocasRouteImport.update({
  id: '/trocas',
  path: '/trocas',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ToteSlugRoute = ToteSlugRouteImport.update({
  id: '/tote/$slug',
  path: '/tote/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/historia': typeof HistoriaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/produto': typeof ProdutoRoute
  '/trocas': typeof TrocasRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tote/$slug': typeof ToteSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/historia': typeof HistoriaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/produto': typeof ProdutoRoute
  '/trocas': typeof TrocasRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tote/$slug': typeof ToteSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/historia': typeof HistoriaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/produto': typeof ProdutoRoute
  '/trocas': typeof TrocasRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tote/$slug': typeof ToteSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/historia'
    | '/privacidade'
    | '/produto'
    | '/trocas'
    | '/blog/$slug'
    | '/tote/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/historia'
    | '/privacidade'
    | '/produto'
    | '/trocas'
    | '/blog/$slug'
    | '/tote/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/historia'
    | '/privacidade'
    | '/produto'
    | '/trocas'
    | '/blog/$slug'
    | '/tote/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  HistoriaRoute: typeof HistoriaRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ProdutoRoute: typeof ProdutoRoute
  TrocasRoute: typeof TrocasRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ToteSlugRoute: typeof ToteSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto': {
      id: '/produto'
      path: '/produto'
      fullPath: '/produto'
      preLoaderRoute: typeof ProdutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trocas': {
      id: '/trocas'
      path: '/trocas'
      fullPath: '/trocas'
      preLoaderRoute: typeof TrocasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tote/$slug': {
      id: '/tote/$slug'
      path: '/tote/$slug'
      fullPath: '/tote/$slug'
      preLoaderRoute: typeof ToteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  HistoriaRoute: HistoriaRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ProdutoRoute: ProdutoRoute,
  TrocasRoute: TrocasRoute,
  BlogSlugRoute: BlogSlugRoute,
  ToteSlugRoute: ToteSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
